export const STATIONS = [
  {
    id: '1',
    name: 'Seaoil Gatuslao',
    brand: 'Seaoil',
    address: 'Gatuslao, Bacolod City',
    distance: 3.5,
    prices: {
      diesel: 82.90,
      gas: 89.22,
      premium: 92.88,
    },
    updatedAt: '19m ago',
    verificationCount: 99,
    coords: { lat: 10.7148, lng: 122.9983 },
    isBestValue: false,
    description: 'A well-maintained station located in the Gatuslao area.',
    history: []
  },
  {
    id: '2',
    name: 'Petron Gatuslao',
    brand: 'Petron',
    address: 'Gatuslao, Bacolod City',
    distance: 5.6,
    prices: {
      diesel: 80.82,
      gas: 86.13,
      premium: 92.59,
    },
    updatedAt: '26m ago',
    verificationCount: 98,
    coords: { lat: 10.6756, lng: 123.0090 },
    isBestValue: false,
    description: 'A well-maintained station located in the Gatuslao area.',
    history: []
  },
  {
    id: '3',
    name: 'Caltex Banago',
    brand: 'Caltex',
    address: 'Banago, Bacolod City',
    distance: 7.7,
    prices: {
      diesel: 81.67,
      gas: 88.86,
      premium: 92.93,
    },
    updatedAt: '52m ago',
    verificationCount: 41,
    coords: { lat: 10.6482, lng: 122.9697 },
    isBestValue: false,
    description: 'A well-maintained station located in the Banago area.',
    history: []
  },
  {
    id: '4',
    name: 'Shell Mansilingan',
    brand: 'Shell',
    address: 'Mansilingan, Bacolod City',
    distance: 6.7,
    prices: {
      diesel: 80.66,
      gas: 89.16,
      premium: 92.03,
    },
    updatedAt: '3m ago',
    verificationCount: 60,
    coords: { lat: 10.6383, lng: 122.9930 },
    isBestValue: false,
    description: 'A well-maintained station located in the Mansilingan area.',
    history: []
  },
  {
    id: '5',
    name: 'Seaoil Magsaysay',
    brand: 'Seaoil',
    address: 'Magsaysay, Bacolod City',
    distance: 2.6,
    prices: {
      diesel: 81.28,
      gas: 89.41,
      premium: 90.14,
    },
    updatedAt: '46m ago',
    verificationCount: 80,
    coords: { lat: 10.7055, lng: 123.0039 },
    isBestValue: false,
    description: 'A well-maintained station located in the Magsaysay area.',
    history: []
  },
  {
    id: '6',
    name: 'CleanFuel Banago',
    brand: 'CleanFuel',
    address: 'Banago, Bacolod City',
    distance: 0.8,
    prices: {
      diesel: 80.98,
      gas: 88.33,
      premium: 92.34,
    },
    updatedAt: '10m ago',
    verificationCount: 51,
    coords: { lat: 10.6977, lng: 122.9901 },
    isBestValue: false,
    description: 'A well-maintained station located in the Banago area.',
    history: []
  },
  {
    id: '7',
    name: 'CleanFuel Villamonte',
    brand: 'CleanFuel',
    address: 'Villamonte, Bacolod City',
    distance: 2.3,
    prices: {
      diesel: 81.18,
      gas: 87.88,
      premium: 92.02,
    },
    updatedAt: '18m ago',
    verificationCount: 42,
    coords: { lat: 10.6797, lng: 122.9515 },
    isBestValue: false,
    description: 'A well-maintained station located in the Villamonte area.',
    history: []
  },
  {
    id: '8',
    name: 'Seaoil Mansilingan',
    brand: 'Seaoil',
    address: 'Mansilingan, Bacolod City',
    distance: 3.8,
    prices: {
      diesel: 83.03,
      gas: 88.76,
      premium: 93.34,
    },
    updatedAt: '53m ago',
    verificationCount: 76,
    coords: { lat: 10.6827, lng: 123.0157 },
    isBestValue: false,
    description: 'A well-maintained station located in the Mansilingan area.',
    history: []
  },
  {
    id: '9',
    name: 'Seaoil Banago',
    brand: 'Seaoil',
    address: 'Banago, Bacolod City',
    distance: 3,
    prices: {
      diesel: 84.30,
      gas: 89.89,
      premium: 92.11,
    },
    updatedAt: '8m ago',
    verificationCount: 65,
    coords: { lat: 10.6965, lng: 122.9668 },
    isBestValue: false,
    description: 'A well-maintained station located in the Banago area.',
    history: []
  },
  {
    id: '10',
    name: 'Petron Gatuslao',
    brand: 'Petron',
    address: 'Gatuslao, Bacolod City',
    distance: 6.2,
    prices: {
      diesel: 84.93,
      gas: 85.97,
      premium: 90.06,
    },
    updatedAt: '51m ago',
    verificationCount: 22,
    coords: { lat: 10.6569, lng: 122.9486 },
    isBestValue: false,
    description: 'A well-maintained station located in the Gatuslao area.',
    history: []
  },
  {
    id: '11',
    name: 'CleanFuel Villamonte',
    brand: 'CleanFuel',
    address: 'Villamonte, Bacolod City',
    distance: 4.9,
    prices: {
      diesel: 83.67,
      gas: 87.89,
      premium: 92.02,
    },
    updatedAt: '10m ago',
    verificationCount: 24,
    coords: { lat: 10.6885, lng: 123.0120 },
    isBestValue: false,
    description: 'A well-maintained station located in the Villamonte area.',
    history: []
  },
  {
    id: '12',
    name: 'Caltex Bata',
    brand: 'Caltex',
    address: 'Bata, Bacolod City',
    distance: 0.6,
    prices: {
      diesel: 80.70,
      gas: 87.79,
      premium: 90.45,
    },
    updatedAt: '14m ago',
    verificationCount: 75,
    coords: { lat: 10.6992, lng: 122.9987 },
    isBestValue: false,
    description: 'A well-maintained station located in the Bata area.',
    history: []
  },
  {
    id: '13',
    name: 'Caltex Mandalagan',
    brand: 'Caltex',
    address: 'Mandalagan, Bacolod City',
    distance: 7.7,
    prices: {
      diesel: 82.58,
      gas: 87.72,
      premium: 90.81,
    },
    updatedAt: '23m ago',
    verificationCount: 44,
    coords: { lat: 10.6854, lng: 122.9623 },
    isBestValue: false,
    description: 'A well-maintained station located in the Mandalagan area.',
    history: []
  },
  {
    id: '14',
    name: 'Petron Luzuriaga',
    brand: 'Petron',
    address: 'Luzuriaga, Bacolod City',
    distance: 8.4,
    prices: {
      diesel: 83.28,
      gas: 88.31,
      premium: 90.77,
    },
    updatedAt: '27m ago',
    verificationCount: 15,
    coords: { lat: 10.7133, lng: 122.9548 },
    isBestValue: false,
    description: 'A well-maintained station located in the Luzuriaga area.',
    history: []
  },
  {
    id: '15',
    name: 'CleanFuel Luzuriaga',
    brand: 'CleanFuel',
    address: 'Luzuriaga, Bacolod City',
    distance: 7.3,
    prices: {
      diesel: 84.40,
      gas: 86.10,
      premium: 92.82,
    },
    updatedAt: '46m ago',
    verificationCount: 57,
    coords: { lat: 10.6843, lng: 122.9662 },
    isBestValue: false,
    description: 'A well-maintained station located in the Luzuriaga area.',
    history: []
  },
  {
    id: '16',
    name: 'Petron Bata',
    brand: 'Petron',
    address: 'Bata, Bacolod City',
    distance: 0.8,
    prices: {
      diesel: 83.34,
      gas: 86.90,
      premium: 94.06,
    },
    updatedAt: '15m ago',
    verificationCount: 89,
    coords: { lat: 10.6974, lng: 123.0016 },
    isBestValue: false,
    description: 'A well-maintained station located in the Bata area.',
    history: []
  },
  {
    id: '17',
    name: 'Petron Taculing',
    brand: 'Petron',
    address: 'Taculing, Bacolod City',
    distance: 1.1,
    prices: {
      diesel: 82.68,
      gas: 87.21,
      premium: 91.54,
    },
    updatedAt: '16m ago',
    verificationCount: 51,
    coords: { lat: 10.6427, lng: 122.9634 },
    isBestValue: false,
    description: 'A well-maintained station located in the Taculing area.',
    history: []
  },
  {
    id: '18',
    name: 'Caltex Araneta',
    brand: 'Caltex',
    address: 'Araneta, Bacolod City',
    distance: 0.9,
    prices: {
      diesel: 83.87,
      gas: 89.46,
      premium: 92.65,
    },
    updatedAt: '19m ago',
    verificationCount: 31,
    coords: { lat: 10.6390, lng: 123.0123 },
    isBestValue: false,
    description: 'A well-maintained station located in the Araneta area.',
    history: []
  },
  {
    id: '19',
    name: 'CleanFuel Mansilingan',
    brand: 'CleanFuel',
    address: 'Mansilingan, Bacolod City',
    distance: 0.5,
    prices: {
      diesel: 84.35,
      gas: 85.40,
      premium: 93.42,
    },
    updatedAt: '27m ago',
    verificationCount: 80,
    coords: { lat: 10.6558, lng: 122.9520 },
    isBestValue: false,
    description: 'A well-maintained station located in the Mansilingan area.',
    history: []
  },
  {
    id: '20',
    name: 'Caltex Burgos',
    brand: 'Caltex',
    address: 'Burgos, Bacolod City',
    distance: 8.2,
    prices: {
      diesel: 82.32,
      gas: 88.75,
      premium: 91.15,
    },
    updatedAt: '15m ago',
    verificationCount: 38,
    coords: { lat: 10.6754, lng: 122.9598 },
    isBestValue: false,
    description: 'A well-maintained station located in the Burgos area.',
    history: []
  },
  {
    id: '21',
    name: 'Petron Gatuslao',
    brand: 'Petron',
    address: 'Gatuslao, Bacolod City',
    distance: 1.1,
    prices: {
      diesel: 81.00,
      gas: 86.62,
      premium: 93.16,
    },
    updatedAt: '56m ago',
    verificationCount: 63,
    coords: { lat: 10.6861, lng: 122.9551 },
    isBestValue: false,
    description: 'A well-maintained station located in the Gatuslao area.',
    history: []
  },
  {
    id: '22',
    name: 'CleanFuel Gatuslao',
    brand: 'CleanFuel',
    address: 'Gatuslao, Bacolod City',
    distance: 1,
    prices: {
      diesel: 82.52,
      gas: 85.94,
      premium: 91.46,
    },
    updatedAt: '52m ago',
    verificationCount: 15,
    coords: { lat: 10.6545, lng: 123.0159 },
    isBestValue: false,
    description: 'A well-maintained station located in the Gatuslao area.',
    history: []
  },
  {
    id: '23',
    name: 'Phoenix Alijis',
    brand: 'Phoenix',
    address: 'Alijis, Bacolod City',
    distance: 5.2,
    prices: {
      diesel: 82.78,
      gas: 86.74,
      premium: 90.73,
    },
    updatedAt: '52m ago',
    verificationCount: 70,
    coords: { lat: 10.7070, lng: 122.9948 },
    isBestValue: false,
    description: 'A well-maintained station located in the Alijis area.',
    history: []
  },
  {
    id: '24',
    name: 'CleanFuel Gatuslao',
    brand: 'CleanFuel',
    address: 'Gatuslao, Bacolod City',
    distance: 4.1,
    prices: {
      diesel: 83.32,
      gas: 86.33,
      premium: 91.81,
    },
    updatedAt: '10m ago',
    verificationCount: 13,
    coords: { lat: 10.6611, lng: 122.9476 },
    isBestValue: false,
    description: 'A well-maintained station located in the Gatuslao area.',
    history: []
  },
  {
    id: '25',
    name: 'CleanFuel Magsaysay',
    brand: 'CleanFuel',
    address: 'Magsaysay, Bacolod City',
    distance: 5.6,
    prices: {
      diesel: 82.78,
      gas: 87.33,
      premium: 94.71,
    },
    updatedAt: '11m ago',
    verificationCount: 74,
    coords: { lat: 10.7128, lng: 122.9692 },
    isBestValue: false,
    description: 'A well-maintained station located in the Magsaysay area.',
    history: []
  },
  {
    id: '26',
    name: 'Caltex Tangub',
    brand: 'Caltex',
    address: 'Tangub, Bacolod City',
    distance: 4.7,
    prices: {
      diesel: 83.40,
      gas: 87.27,
      premium: 93.14,
    },
    updatedAt: '29m ago',
    verificationCount: 12,
    coords: { lat: 10.6953, lng: 122.9777 },
    isBestValue: false,
    description: 'A well-maintained station located in the Tangub area.',
    history: []
  },
  {
    id: '27',
    name: 'Shell Sum-ag',
    brand: 'Shell',
    address: 'Sum-ag, Bacolod City',
    distance: 2.8,
    prices: {
      diesel: 83.42,
      gas: 86.37,
      premium: 94.52,
    },
    updatedAt: '44m ago',
    verificationCount: 4,
    coords: { lat: 10.7013, lng: 122.9650 },
    isBestValue: false,
    description: 'A well-maintained station located in the Sum-ag area.',
    history: []
  },
  {
    id: '28',
    name: 'Shell Galo',
    brand: 'Shell',
    address: 'Galo, Bacolod City',
    distance: 6.7,
    prices: {
      diesel: 84.57,
      gas: 87.74,
      premium: 90.16,
    },
    updatedAt: '31m ago',
    verificationCount: 45,
    coords: { lat: 10.6769, lng: 123.0087 },
    isBestValue: false,
    description: 'A well-maintained station located in the Galo area.',
    history: []
  },
  {
    id: '29',
    name: 'Phoenix Singcang-Airport',
    brand: 'Phoenix',
    address: 'Singcang-Airport, Bacolod City',
    distance: 4.4,
    prices: {
      diesel: 84.15,
      gas: 86.65,
      premium: 92.71,
    },
    updatedAt: '38m ago',
    verificationCount: 43,
    coords: { lat: 10.6665, lng: 122.9464 },
    isBestValue: false,
    description: 'A well-maintained station located in the Singcang-Airport area.',
    history: []
  },
  {
    id: '30',
    name: 'Petron Banago',
    brand: 'Petron',
    address: 'Banago, Bacolod City',
    distance: 3.2,
    prices: {
      diesel: 84.14,
      gas: 89.25,
      premium: 94.64,
    },
    updatedAt: '45m ago',
    verificationCount: 84,
    coords: { lat: 10.7158, lng: 122.9744 },
    isBestValue: false,
    description: 'A well-maintained station located in the Banago area.',
    history: []
  },
  {
    id: '31',
    name: 'Caltex Mandalagan',
    brand: 'Caltex',
    address: 'Mandalagan, Bacolod City',
    distance: 4,
    prices: {
      diesel: 82.05,
      gas: 87.21,
      premium: 91.52,
    },
    updatedAt: '40m ago',
    verificationCount: 40,
    coords: { lat: 10.6524, lng: 122.9962 },
    isBestValue: false,
    description: 'A well-maintained station located in the Mandalagan area.',
    history: []
  },
  {
    id: '32',
    name: 'CleanFuel Burgos',
    brand: 'CleanFuel',
    address: 'Burgos, Bacolod City',
    distance: 7.4,
    prices: {
      diesel: 82.29,
      gas: 85.95,
      premium: 93.03,
    },
    updatedAt: '10m ago',
    verificationCount: 5,
    coords: { lat: 10.6677, lng: 122.9628 },
    isBestValue: false,
    description: 'A well-maintained station located in the Burgos area.',
    history: []
  },
  {
    id: '33',
    name: 'CleanFuel Araneta',
    brand: 'CleanFuel',
    address: 'Araneta, Bacolod City',
    distance: 3.5,
    prices: {
      diesel: 80.98,
      gas: 88.94,
      premium: 92.12,
    },
    updatedAt: '20m ago',
    verificationCount: 49,
    coords: { lat: 10.6893, lng: 123.0057 },
    isBestValue: false,
    description: 'A well-maintained station located in the Araneta area.',
    history: []
  },
  {
    id: '34',
    name: 'Shell Taculing',
    brand: 'Shell',
    address: 'Taculing, Bacolod City',
    distance: 6.8,
    prices: {
      diesel: 81.05,
      gas: 87.55,
      premium: 92.93,
    },
    updatedAt: '16m ago',
    verificationCount: 35,
    coords: { lat: 10.7143, lng: 123.0087 },
    isBestValue: false,
    description: 'A well-maintained station located in the Taculing area.',
    history: []
  },
  {
    id: '35',
    name: 'Petron Magsaysay',
    brand: 'Petron',
    address: 'Magsaysay, Bacolod City',
    distance: 4.1,
    prices: {
      diesel: 82.95,
      gas: 88.51,
      premium: 90.07,
    },
    updatedAt: '53m ago',
    verificationCount: 15,
    coords: { lat: 10.6471, lng: 122.9561 },
    isBestValue: false,
    description: 'A well-maintained station located in the Magsaysay area.',
    history: []
  },
  {
    id: '36',
    name: 'Caltex Mansilingan',
    brand: 'Caltex',
    address: 'Mansilingan, Bacolod City',
    distance: 3.5,
    prices: {
      diesel: 80.86,
      gas: 85.39,
      premium: 91.49,
    },
    updatedAt: '10m ago',
    verificationCount: 60,
    coords: { lat: 10.6538, lng: 122.9767 },
    isBestValue: false,
    description: 'A well-maintained station located in the Mansilingan area.',
    history: []
  },
  {
    id: '37',
    name: 'Caltex Estefania',
    brand: 'Caltex',
    address: 'Estefania, Bacolod City',
    distance: 5.3,
    prices: {
      diesel: 81.88,
      gas: 86.25,
      premium: 91.28,
    },
    updatedAt: '44m ago',
    verificationCount: 66,
    coords: { lat: 10.6394, lng: 122.9966 },
    isBestValue: false,
    description: 'A well-maintained station located in the Estefania area.',
    history: []
  },
  {
    id: '38',
    name: 'CleanFuel Alijis',
    brand: 'CleanFuel',
    address: 'Alijis, Bacolod City',
    distance: 1.6,
    prices: {
      diesel: 80.39,
      gas: 85.74,
      premium: 92.62,
    },
    updatedAt: '26m ago',
    verificationCount: 75,
    coords: { lat: 10.7129, lng: 123.0012 },
    isBestValue: false,
    description: 'A well-maintained station located in the Alijis area.',
    history: []
  },
  {
    id: '39',
    name: 'Phoenix Tangub',
    brand: 'Phoenix',
    address: 'Tangub, Bacolod City',
    distance: 4.5,
    prices: {
      diesel: 83.49,
      gas: 88.64,
      premium: 93.64,
    },
    updatedAt: '22m ago',
    verificationCount: 27,
    coords: { lat: 10.6514, lng: 122.9767 },
    isBestValue: false,
    description: 'A well-maintained station located in the Tangub area.',
    history: []
  },
  {
    id: '40',
    name: 'Phoenix Alijis',
    brand: 'Phoenix',
    address: 'Alijis, Bacolod City',
    distance: 2.9,
    prices: {
      diesel: 81.92,
      gas: 88.62,
      premium: 92.28,
    },
    updatedAt: '26m ago',
    verificationCount: 87,
    coords: { lat: 10.7061, lng: 122.9860 },
    isBestValue: false,
    description: 'A well-maintained station located in the Alijis area.',
    history: []
  },
  {
    id: '41',
    name: 'Phoenix Alijis',
    brand: 'Phoenix',
    address: 'Alijis, Bacolod City',
    distance: 7.6,
    prices: {
      diesel: 82.27,
      gas: 89.91,
      premium: 93.77,
    },
    updatedAt: '7m ago',
    verificationCount: 4,
    coords: { lat: 10.6484, lng: 122.9804 },
    isBestValue: false,
    description: 'A well-maintained station located in the Alijis area.',
    history: []
  },
  {
    id: '42',
    name: 'Caltex Sum-ag',
    brand: 'Caltex',
    address: 'Sum-ag, Bacolod City',
    distance: 0.7,
    prices: {
      diesel: 82.84,
      gas: 89.69,
      premium: 90.93,
    },
    updatedAt: '38m ago',
    verificationCount: 37,
    coords: { lat: 10.7040, lng: 123.0088 },
    isBestValue: false,
    description: 'A well-maintained station located in the Sum-ag area.',
    history: []
  },
  {
    id: '43',
    name: 'Shell Banago',
    brand: 'Shell',
    address: 'Banago, Bacolod City',
    distance: 7.1,
    prices: {
      diesel: 81.53,
      gas: 88.31,
      premium: 93.30,
    },
    updatedAt: '45m ago',
    verificationCount: 25,
    coords: { lat: 10.6771, lng: 123.0180 },
    isBestValue: false,
    description: 'A well-maintained station located in the Banago area.',
    history: []
  },
  {
    id: '44',
    name: 'Petron Gatuslao',
    brand: 'Petron',
    address: 'Gatuslao, Bacolod City',
    distance: 8.4,
    prices: {
      diesel: 80.59,
      gas: 85.11,
      premium: 93.03,
    },
    updatedAt: '37m ago',
    verificationCount: 12,
    coords: { lat: 10.6842, lng: 123.0058 },
    isBestValue: false,
    description: 'A well-maintained station located in the Gatuslao area.',
    history: []
  },
  {
    id: '45',
    name: 'Petron Singcang-Airport',
    brand: 'Petron',
    address: 'Singcang-Airport, Bacolod City',
    distance: 8,
    prices: {
      diesel: 83.80,
      gas: 86.48,
      premium: 92.30,
    },
    updatedAt: '47m ago',
    verificationCount: 99,
    coords: { lat: 10.6706, lng: 122.9790 },
    isBestValue: false,
    description: 'A well-maintained station located in the Singcang-Airport area.',
    history: []
  },
  {
    id: '46',
    name: 'Petron Burgos',
    brand: 'Petron',
    address: 'Burgos, Bacolod City',
    distance: 5,
    prices: {
      diesel: 81.03,
      gas: 88.02,
      premium: 90.64,
    },
    updatedAt: '19m ago',
    verificationCount: 54,
    coords: { lat: 10.6496, lng: 122.9973 },
    isBestValue: false,
    description: 'A well-maintained station located in the Burgos area.',
    history: []
  },
  {
    id: '47',
    name: 'CleanFuel Gatuslao',
    brand: 'CleanFuel',
    address: 'Gatuslao, Bacolod City',
    distance: 1.2,
    prices: {
      diesel: 82.30,
      gas: 88.74,
      premium: 93.65,
    },
    updatedAt: '40m ago',
    verificationCount: 99,
    coords: { lat: 10.7042, lng: 122.9809 },
    isBestValue: false,
    description: 'A well-maintained station located in the Gatuslao area.',
    history: []
  },
  {
    id: '48',
    name: 'Seaoil Luzuriaga',
    brand: 'Seaoil',
    address: 'Luzuriaga, Bacolod City',
    distance: 3.9,
    prices: {
      diesel: 80.55,
      gas: 88.96,
      premium: 90.61,
    },
    updatedAt: '42m ago',
    verificationCount: 57,
    coords: { lat: 10.6903, lng: 122.9704 },
    isBestValue: false,
    description: 'A well-maintained station located in the Luzuriaga area.',
    history: []
  },
  {
    id: '49',
    name: 'Petron Tangub',
    brand: 'Petron',
    address: 'Tangub, Bacolod City',
    distance: 8.1,
    prices: {
      diesel: 82.36,
      gas: 87.75,
      premium: 92.40,
    },
    updatedAt: '11m ago',
    verificationCount: 22,
    coords: { lat: 10.6959, lng: 122.9441 },
    isBestValue: false,
    description: 'A well-maintained station located in the Tangub area.',
    history: []
  },
  {
    id: '50',
    name: 'Caltex Alijis',
    brand: 'Caltex',
    address: 'Alijis, Bacolod City',
    distance: 2.5,
    prices: {
      diesel: 82.23,
      gas: 86.56,
      premium: 93.26,
    },
    updatedAt: '33m ago',
    verificationCount: 10,
    coords: { lat: 10.6719, lng: 122.9630 },
    isBestValue: false,
    description: 'A well-maintained station located in the Alijis area.',
    history: []
  },
];

export const TREND_DATA = [
  { name: 'MON', gas: 85.20, diesel: 80.50, premium: 90.90 },
  { name: 'TUE', gas: 85.50, diesel: 80.80, premium: 91.20 },
  { name: 'WED', gas: 86.80, diesel: 81.00, premium: 91.40 },
  { name: 'THU', gas: 86.10, diesel: 81.20, premium: 91.60 },
  { name: 'FRI', gas: 87.20, diesel: 81.30, premium: 91.70 },
  { name: 'SAT', gas: 87.80, diesel: 81.40, premium: 91.80 },
  { name: 'SUN', gas: 88.10, diesel: 81.50, premium: 91.90 },
];

export const ACTIVITY = [
  {
    id: '1',
    type: 'price_hike',
    station: 'Shell Lacson',
    change: '+₱0.30',
    reason: 'Market adjustment',
    time: '1h ago',
  },
  {
    id: '2',
    type: 'discount',
    station: 'Petron Mansilingan',
    change: '-₱0.80',
    reason: 'Weekend Promo',
    time: '3h ago',
  }
];

export const TREND_DATA_30D = Array.from({ length: 30 }, (_, i) => ({
  name: `Day ${i + 1}`,
  gas: 85.20 + Math.sin(i / 5) * 2 + (i / 10),
  diesel: 80.50 + Math.sin(i / 5) * 1.5 + (i / 12),
  premium: 90.90 + Math.sin(i / 5) * 2.2 + (i / 8),
}));

export const EXTENDED_ACTIVITY = [
  ...ACTIVITY,
  {
    id: '3',
    type: 'price_hike',
    station: 'Caltex Mandalagan',
    change: '+₱0.45',
    reason: 'Oil supply drop',
    time: '5h ago',
  },
  {
    id: '4',
    type: 'discount',
    station: 'Phoenix Mansilingan',
    change: '-₱1.20',
    reason: 'Local competition',
    time: '8h ago',
  },
  {
    id: '5',
    type: 'price_hike',
    station: 'Petron Araneta',
    change: '+₱0.15',
    reason: 'Inflation adjustment',
    time: '12h ago',
  },
  {
    id: '6',
    type: 'discount',
    station: 'Shell B.S. Aquino',
    change: '-₱0.50',
    reason: 'App exclusive promo',
    time: '1d ago',
  },
  {
    id: '7',
    type: 'price_hike',
    station: 'Shell Lacson',
    change: '+₱0.75',
    reason: 'Global market surge',
    time: '2d ago',
  }
];

export const REGIONAL_PRICES = [
  { area: 'LACSON STREET', gas: 88.80, diesel: 84.50, premium: 93.90 },
  { area: 'ARANETA STREET', gas: 89.40, diesel: 85.10, premium: 94.50 },
  { area: 'MANSILINGAN', gas: 86.90, diesel: 82.80, premium: 91.50 },
  { area: 'BURGOS STREET', gas: 89.20, diesel: 84.90, premium: 94.10 },
  { area: 'MANDALAGAN', gas: 88.10, diesel: 83.90, premium: 93.20 },
];
